apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - image: nginx
          name: nginx-cont
