apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - image: busybox
      name: busybox
      command: ['sh', '-c', 'echo successful > /output/success.txt']
      volumeMounts:
        - mountPath: /output
          name: my-volume
  volumes:
    - hostPath:
        path: /var/data
      name: my-volume


