apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: my-volume
          mountPath: "/logs"
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvs-sc
