apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.128.0.7
    path: /opt/sfw
    readOnly: false
