apiVersion: v1
kind: Pod
metadata:
  name: pvc-volume
spec:
  containers:
    - image: busybox
      name: busybox
      command: ['sh', '-c', 'while true; do echo siva::: >> /output/output.txt; sleep 5; done']
      volumeMounts:
        - name: my-volume
          mountPath: /output
  volumes:
    - persistentVolumeClaim:
        claimName: nfs-claim
      name: my-volume
