apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - image: nginx:stable-otel
          name: nginx-cont
  strategy:
    type: Recreate

