apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - image: nginx:stable-otel
          name: nginx-cont
  strategy:
    type: RollingUpdate   # by default it will pick up, not manadatory to write
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
